services:
    app:
        build:
            context: ./docker/8.5
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: nutria/app
        container_name: nutria_app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8002}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'off'
        volumes:
            - '.:/var/www/html'
            - './docker/8.5/supervisord.prod.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - nutria
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    pgsql:
        image: 'pgvector/pgvector:pg17'
        container_name: nutria_pgsql
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'nutria_pgsql:/var/lib/postgresql/data'
        networks:
            - nutria
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            interval: 10s
            retries: 5
            timeout: 5s
        restart: unless-stopped

    redis:
        image: 'redis:alpine'
        container_name: nutria_redis
        volumes:
            - 'nutria_redis:/data'
        networks:
            - nutria
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            interval: 10s
            retries: 3
            timeout: 5s
        restart: unless-stopped

networks:
    nutria:
        driver: bridge

volumes:
    nutria_pgsql:
        driver: local
    nutria_redis:
        driver: local
